import Link from "next/link";
import {AuroraScene} from "@/components/aurora-scene";
import {Brand} from "@/components/brand";
const models=[["01","ChatGPT","6 Astra · 5.6 Sol · 5.6 Terra"],["02","Claude","Fable 5 · Fable 5.1 · Opus 5"]];
export default function Home(){return <div className="site editorial"><header className="container nav"><Brand/><nav className="nav-links"><a href="#models">Модели</a><Link href="/docs">Подключение</Link><Link href="/login">Войти</Link><Link className="button primary" href="/signup">Получить ключ</Link></nav></header><main>
<section className="container kinetic-hero"><div className="hero-heading"><p className="eyebrow">API для текста и кода</p><h1>ChatGPT.<br/><span>Claude.</span></h1><div className="hero-bottom"><p>Один ключ. Общий баланс.<br/>Оплата за использованные токены.</p><Link className="button primary" href="/signup">Начать работу</Link></div></div><AuroraScene/><div className="hero-footnote"><span>1 000 000 токенов / 50 ₽</span><a href="#models">Модели и подключение ↓</a></div></section>
<section id="models" className="container catalogue-section"><div className="section-heading reveal"><span className="eyebrow">01 / Модели</span><h2>Выберите модель.<br/>Сохраните привычный процесс.</h2></div>{models.map(([num,name,versions])=><div className={"model-spread depth-panel "+(num==="02"?"claude-spread":"")} key={name}><div className="spread-info reveal"><span className="spread-number">{num}</span><h3>{name}</h3><p>{versions}</p><Link href="/docs">Как подключить <span>↗</span></Link></div><div className="spectrum" aria-hidden="true">{Array.from({length:24},(_,i)=><i key={i} style={{"--i":i} as React.CSSProperties}/>)}</div></div>)}<p className="catalogue-note">Названия в каталоге — алиасы Werty. Актуальная доступность и конфигурация: GET /v1/models.</p></section>
<section className="container usage-section"><div className="section-heading reveal"><span className="eyebrow">02 / Расходы</span><h2>Всё видно<br/>в кабинете.</h2><p>Баланс, история запросов и расход каждой модели.</p></div><div className="usage-stage depth-panel"><div className="usage-preview reveal"><div className="preview-bar">Пример статистики / 7 дней</div><div className="metrics"><div className="metric"><label>Баланс</label><strong>12.48M</strong></div><div className="metric"><label>Вход</label><strong>4.20M</strong></div><div className="metric"><label>Выход</label><strong>1.84M</strong></div></div><div className="chart"><svg viewBox="0 0 700 160" aria-label="Пример графика расхода"><path d="M0 132 C70 121 95 88 155 104 S250 42 320 69 S421 94 480 43 S610 31 700 12" fill="none" strokeWidth="3"/></svg></div></div></div></section>
<section className="container connect-section reveal"><div><span className="eyebrow">03 / Подключение</span><h2>Работайте там,<br/>где удобно.</h2><p>Инструкции, конфигурации и готовые примеры запросов.</p><Link className="button primary" href="/docs">Открыть документацию</Link></div><div className="app-list">{[["ChatGPT","chatgpt"],["Claude Desktop","claude"],["Cursor","cursor"],["OpenCode","opencode"],["Терминал / PowerShell","terminal"],["VS Code","vscode"]].map(([name,id])=><Link key={id} href={"/docs#"+id}>{name}<span>↗</span></Link>)}</div></section>
</main><footer className="container footer"><Brand/><div className="footer-links"><Link href="/login">Войти</Link><Link href="/docs">Документация</Link><Link href="/terms">Условия</Link><Link href="/privacy">Конфиденциальность</Link></div><span>© 2026 Werty</span></footer></div>}
