import Link from "next/link";
import {Brand} from "@/components/brand";
import {CodeBlock} from "@/components/code-block";
export const metadata={title:"Подключение приложений"};
const applications=[["start","Начало"],["chatgpt","ChatGPT App"],["claude","Claude App"],["opencode","OpenCode"],["cursor","Cursor"],["terminal","Терминал"],["powershell","PowerShell"],["claude-code","Claude Code"],["vscode","VS Code"]];
const bash=String.raw`read -rsp "Werty API key: " WERTY_API_KEY; echo
export WERTY_API_KEY
curl --fail-with-body https://wertyai.online/v1/chat/completions \
  -H "Authorization: Bearer $WERTY_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"model":"gpt-6-astra","messages":[{"role":"user","content":"Привет!"}],"max_tokens":1024}'`;
const powershell=`$secret = Read-Host "Werty API key" -AsSecureString
$credential = [PSCredential]::new("werty", $secret)
$headers = @{ Authorization = "Bearer " + $credential.GetNetworkCredential().Password }
$payload = @{
  model = "gpt-6-astra"
  messages = @(@{ role = "user"; content = "Привет!" })
  max_tokens = 1024
} | ConvertTo-Json -Depth 5
$result = Invoke-RestMethod -Method Post \`
  -Uri "https://wertyai.online/v1/chat/completions" \`
  -Headers $headers -ContentType "application/json; charset=utf-8" \`
  -Body ([Text.Encoding]::UTF8.GetBytes($payload))
$result.choices[0].message.content`;
const openCode=JSON.stringify({$schema:"https://opencode.ai/config.json",provider:{werty:{npm:"@ai-sdk/openai-compatible",name:"Werty",options:{baseURL:"https://wertyai.online/v1",apiKey:"{env:WERTY_API_KEY}"},models:{"gpt-6-astra":{name:"ChatGPT 6 Astra"}}}},model:"werty/gpt-6-astra"},null,2);
export default function Docs(){return <div className="site"><header className="container nav"><Brand/><nav className="nav-links"><Link href="/">Главная</Link><Link href="/dashboard">Кабинет</Link><Link className="button primary" href="/dashboard/api-keys">Мои ключи</Link></nav></header><main className="container docs-layout"><aside className="docs-sidebar"><div className="eyebrow">Подключение</div>{applications.map(([id,name])=><a key={id} href={"#"+id}>{name}</a>)}</aside><article className="docs-main"><div className="eyebrow">Werty / Documentation</div><h1>Ваши инструменты.<br/>Один ключ.</h1><p className="hero-copy">Выберите приложение и настройте подключение. Здесь указаны и рабочие примеры, и ограничения текущего API.</p>
<section id="start" className="doc-section"><h2>Начало</h2><ol><li>Создайте аккаунт и подтвердите email.</li><li>Сохраните ключ в разделе «API keys» и пополните баланс.</li><li>Используйте base URL ниже. Идентификаторы доступных моделей можно получить запросом GET /v1/models с вашим Bearer-ключом.</li></ol><CodeBlock label="ПАРАМЕТРЫ" code={"Base URL: https://wertyai.online/v1\nChat: POST /v1/chat/completions\nModels: GET /v1/models\nAuthorization: Bearer <WERTY_API_KEY>\nModel: gpt-6-astra"}/><p>Сейчас поддерживаются текстовые messages с ролями system, user, assistant, параметры max_tokens, temperature и stream. Изображения, tools, tool_calls, Responses API и Anthropic Messages API пока не поддерживаются. Поэтому наличие настройки провайдера в редакторе ещё не означает совместимость его агентного режима.</p><p>Названия моделей в Werty — алиасы маршрутов. Фактическая модель провайдера указана в поле backend_model ответа /v1/models.</p></section>
<section id="chatgpt" className="doc-section"><span className="doc-badge">CHATGPT / CUSTOM GPT ACTION</span><h2>ChatGPT App</h2><p>Подключите Werty как действие своего GPT. ChatGPT отправит выбранный запрос в Werty и покажет полученный ответ. Это внешний инструмент внутри чата; он не заменяет основную модель ChatGPT.</p><ol><li>На сайте ChatGPT откройте редактор своего GPT → Configure → Actions → Create new action. Нужен аккаунт с доступом к созданию GPT и Actions.</li><li>Выберите Import from URL и вставьте адрес схемы ниже.</li><li>В Authentication выберите API Key → Bearer и введите ключ Werty.</li><li>В Instructions вставьте инструкцию ниже. Укажите Privacy policy URL: https://wertyai.online/privacy.</li><li>В Preview попросите отправить «Привет» модели gpt-6-astra через askWerty и подтвердите вызов. Проверьте списание в кабинете Werty.</li><li>Сохраните GPT с доступом «Только я». Откройте его в ChatGPT. Запросы действия оплачиваются с баланса владельца указанного ключа.</li></ol><CodeBlock label="IMPORT FROM URL" code="https://wertyai.online/integrations/openapi.json"/><CodeBlock label="GPT INSTRUCTIONS" code="Когда пользователь просит ответ Werty, используй askWerty. Уточни модель, если она не указана; по умолчанию gpt-6-astra. Передавай только текст, который пользователь хочет отправить. Используй stream=false. Покажи ответ Werty без приписывания его основной модели ChatGPT. Если вызов не удался, сообщи об ошибке."/ ><p>Доступность Actions зависит от аккаунта и политики организации; Pro mode не поддерживает Actions. Если редактор вашей версии уже переведён на Plugins, не ищите отсутствующее меню Actions: используйте доступный в аккаунте путь миграции и проверьте совместимость перед переносом.</p><p><a href="https://help.openai.com/en/articles/9442513">Официальная инструкция Actions</a></p></section>
<section id="claude" className="doc-section"><span className="doc-badge">CLAUDE DESKTOP / LOCAL MCP</span><h2>Claude App</h2><p>Для Claude Desktop подготовлен локальный MCP-коннектор с инструментом ask_werty. Он отправляет запросы в Werty через ваш API key. Основной Claude вызывает инструмент и получает ответ выбранной модели.</p><ol><li>Установите Node.js 20 или новее. В терминале проверьте node --version.</li><li><a href="/integrations/werty-mcp.mjs" download>Скачайте werty-mcp.mjs</a> и сохраните, например, в C:\Werty\werty-mcp.mjs.</li><li>В Claude Desktop откройте Settings → Developer → Edit Config. На Windows файл находится в %APPDATA%\Claude\claude_desktop_config.json.</li><li>Добавьте блок ниже в mcpServers, сохранив существующие серверы. Замените путь и WERTY_API_KEY. Ключ хранится локально в этом файле: не публикуйте его.</li><li>Полностью закройте и заново откройте Claude Desktop. Проверьте, что появился инструмент ask_werty.</li><li>Напишите: «Через ask_werty спроси gpt-6-astra: Привет». Подтвердите вызов. Запрос расходует баланс Werty.</li></ol><CodeBlock label="claude_desktop_config.json" code={JSON.stringify({mcpServers:{werty:{command:"node",args:["C:/Werty/werty-mcp.mjs"],env:{WERTY_API_KEY:"ВСТАВЬТЕ_КЛЮЧ_WERTY"}}}},null,2)}/><p>На macOS используйте абсолютный путь к скрипту и при необходимости к node. Этот локальный коннектор работает в Desktop. Для Claude в браузере или на телефоне требуется отдельно размещённый remote MCP-сервер; URL /v1 не является MCP-адресом.</p><p><a href="https://modelcontextprotocol.io/docs/develop/connect-local-servers">Официальная настройка локального MCP в Claude Desktop</a></p></section>
<section id="opencode" className="doc-section"><span className="doc-badge">КОНФИГУРАЦИЯ ПРОВАЙДЕРА / ОГРАНИЧЕННАЯ СОВМЕСТИМОСТЬ</span><h2>OpenCode</h2><p>Для версий OpenCode с конфигурацией provider/npm создайте opencode.json в папке проекта. Ключ храните в переменной WERTY_API_KEY, а не в файле конфигурации.</p><CodeBlock label="opencode.json" code={openCode}/><p>Выберите werty/gpt-6-astra в списке моделей. Конфигурация задаёт подключение, но агент OpenCode отправляет tools и другие поля, которых пока нет в Werty API: такой запрос получит 400. Для проверки текстового запроса используйте curl. Для OpenCode v2 сверяйте формат конфигурации с документацией установленной версии.</p><p><a href="https://opencode.ai/docs/providers/#custom-provider">Настройка пользовательского провайдера</a></p></section>
<section id="cursor" className="doc-section"><span className="doc-badge">ТЕКСТОВЫЕ ЗАПРОСЫ / ЗАВИСИТ ОТ ВЕРСИИ</span><h2>Cursor</h2><ol><li>Откройте Cursor Settings → Models → API Keys.</li><li>Если в вашей версии доступна Override OpenAI Base URL, укажите https://wertyai.online/v1.</li><li>В поле OpenAI API Key вставьте ключ Werty. Добавьте идентификатор gpt-6-astra и выберите его в чате.</li></ol><p>Проверяйте обычный текстовый запрос. Agent, Tab и запросы с tools не поддерживаются текущим Werty API. Если проверка ключа запрашивает стандартную модель OpenAI, она может завершиться ошибкой: используйте именно ID из /v1/models. Поддержка произвольных endpoint зависит от версии Cursor.</p><p><a href="https://cursor.com/docs">Документация Cursor</a></p></section>
<section id="terminal" className="doc-section"><span className="doc-badge">ПОДДЕРЖИВАЕТСЯ</span><h2>Терминал</h2><p>Пример для Bash на macOS, Linux или WSL с установленным curl. Ключ вводится скрыто. Ответ возвращается в JSON; текст находится в choices[0].message.content.</p><CodeBlock label="BASH / CURL" code={bash}/></section>
<section id="powershell" className="doc-section"><span className="doc-badge">ПОДДЕРЖИВАЕТСЯ</span><h2>PowerShell</h2><p>Пример для Windows PowerShell 5.1 и PowerShell 7. Вставьте команды, введите ключ и отправьте запрос. UTF-8 сохраняет русский текст.</p><CodeBlock label="POWERSHELL" code={powershell}/></section>
<section id="claude-code" className="doc-section"><span className="doc-badge">ТРЕБУЕТСЯ АДАПТЕР ПРОТОКОЛА</span><h2>Claude Code</h2><p>Claude Code требует совместимый шлюз с поддержкой формата Anthropic, инструментов и потоковых событий. Текущий /v1/chat/completions Werty не является таким шлюзом. Простая подстановка Werty в ANTHROPIC_BASE_URL не заработает.</p><p>Для подключения сначала нужен адаптер Anthropic Messages → Werty и поддержка tools на сервере. После этого адрес адаптера указывается в ANTHROPIC_BASE_URL, а его ключ — в ANTHROPIC_AUTH_TOKEN. Готового адаптера в этом проекте пока нет.</p><p><a href="https://code.claude.com/docs/en/llm-gateway">Требования Claude Code к шлюзам</a></p></section>
<section id="vscode" className="doc-section"><span className="doc-badge">CUSTOM ENDPOINT / ТЕКСТОВЫЙ ЧАТ</span><h2>VS Code</h2><ol><li>В панели Chat откройте выбор модели → Manage Language Models.</li><li>Нажмите Add Models → Custom Endpoint, задайте имя Werty и API key.</li><li>Выберите API type: Chat Completions. В открывшемся chatLanguageModels.json задайте ID gpt-6-astra и URL https://wertyai.online/v1/chat/completions.</li><li>Отключите tool calling и vision для этой модели. Выберите её для обычного текстового чата.</li></ol><p>Настройка доступна в версиях VS Code с Custom Endpoint; корпоративная политика может ограничивать свои ключи. Agent и запросы с дополнительными неподдерживаемыми полями могут возвращать 400.</p><p><a href="https://code.visualstudio.com/docs/agent-customization/language-models#_add-a-custom-endpoint-model">Настройка Custom Endpoint в VS Code</a></p></section>
<section className="doc-section"><h2>Если запрос не проходит</h2><p>401 — проверьте ключ. 402 — пополните баланс. 400 — проверьте поля запроса и ID модели. 429 — повторите позже. 503 — маршрут модели временно недоступен. Сначала выполните пример из терминала: он проверяет базовое подключение независимо от редактора.</p></section>
</article></main></div>}
